apiVersion: v1
kind: Service
metadata:
  name: testkuber
spec:
  selector:
    app: testkuber
  ports:
    - port: 4200
      targetPort: 3000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testkuber

spec:
  replicas: 1
  selector:
    matchLabels:
      app: testkuber
  template:
    metadata:
      labels:
        app: testkuber
    spec:
      containers:
        - name: app
          image: haywardj/kubernetes-testing
          ports:
          - containerPort: 3000
          imagePullPolicy: Always